title: Hello, world! I'm Sy An
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Sy An # add your name
author-img: avatar.jpg # add your photo
about-author: The secret of getting ahead is to get started  <br/> - <br/> ***Mark Twain*** # add description
social-twitter: twitter.com/An63314251 # add your Twitter handle
social-facebook: facebook.com/an.sy.97 # add your Facebook handle
social-github: github.com/NguyenSyAn # add your Github handle
social-linkedin: linkedin.com/in/an-nguyen-613178118 # add your Linkedin handle
social-email: syan224@gmail.com # add your Email address

# Disqus
discus-identifier: # add your discus identifier

# Tracker
analytics: UA-143006386-1 # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

sass:
  style: compressed
